"""make application resume nullable

Revision ID: d2231f53e772
Revises: b9eb772580e7
Create Date: 2026-08-23 02:01:20.592193
"""
from alembic import op
import sqlalchemy as sa


revision = 'd2231f53e772'
down_revision = 'b9eb772580e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admins_user_id', table_name='admins')
    op.alter_column('applications', 'resume_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_applications_candidate_id', table_name='applications')
    op.drop_index('ix_applications_job_id', table_name='applications')
    op.drop_index('ix_applications_job_status_applied_at', table_name='applications')
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_constraint('uq_applications_application_code', 'applications', type_='unique')
    op.drop_index('ix_applications_application_code', table_name='applications')
    op.create_index(op.f('ix_applications_application_code'), 'applications', ['application_code'], unique=True)
    op.drop_constraint('fk_applications_resume', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_candidates_name', table_name='candidates')
    op.drop_index('ix_candidates_user_id', table_name='candidates')
    op.alter_column('education', 'passing_year',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('ix_education_candidate_id', table_name='education')
    op.drop_index('ix_experience_candidate_id', table_name='experience')
    op.drop_index('ix_job_requisitions_department', table_name='job_requisitions')
    op.drop_index('ix_job_requisitions_location', table_name='job_requisitions')
    op.drop_index('ix_job_requisitions_status', table_name='job_requisitions')
    op.drop_index('ix_job_requisitions_status_created_at', table_name='job_requisitions')
    op.drop_index('ix_job_requisitions_title_trgm', table_name='job_requisitions', postgresql_using='gin')
    op.drop_constraint('uq_job_requisitions_code', 'job_requisitions', type_='unique')
    op.create_index(op.f('ix_job_requisitions_requisition_code'), 'job_requisitions', ['requisition_code'], unique=True)
    op.drop_index('ix_notifications_admin_recipient', table_name='notifications', postgresql_where='(admin_recipient_id IS NOT NULL)')
    op.drop_index('ix_notifications_application_id', table_name='notifications')
    op.drop_index('ix_notifications_candidate_recipient', table_name='notifications', postgresql_where='(candidate_recipient_id IS NOT NULL)')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index('ix_resumes_candidate_id', table_name='resumes')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('ix_users_role', table_name='users')
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('ix_resumes_candidate_id', 'resumes', ['candidate_id'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_candidate_recipient', 'notifications', ['candidate_recipient_id'], unique=False, postgresql_where='(candidate_recipient_id IS NOT NULL)')
    op.create_index('ix_notifications_application_id', 'notifications', ['application_id'], unique=False)
    op.create_index('ix_notifications_admin_recipient', 'notifications', ['admin_recipient_id'], unique=False, postgresql_where='(admin_recipient_id IS NOT NULL)')
    op.drop_index(op.f('ix_job_requisitions_requisition_code'), table_name='job_requisitions')
    op.create_unique_constraint('uq_job_requisitions_code', 'job_requisitions', ['requisition_code'])
    op.create_index('ix_job_requisitions_title_trgm', 'job_requisitions', [sa.text("to_tsvector('english'::regconfig, title::text)")], unique=False, postgresql_using='gin')
    op.create_index('ix_job_requisitions_status_created_at', 'job_requisitions', ['status', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_job_requisitions_status', 'job_requisitions', ['status'], unique=False)
    op.create_index('ix_job_requisitions_location', 'job_requisitions', ['location'], unique=False)
    op.create_index('ix_job_requisitions_department', 'job_requisitions', ['department'], unique=False)
    op.create_index('ix_experience_candidate_id', 'experience', ['candidate_id'], unique=False)
    op.create_index('ix_education_candidate_id', 'education', ['candidate_id'], unique=False)
    op.alter_column('education', 'passing_year',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.create_index('ix_candidates_user_id', 'candidates', ['user_id'], unique=False)
    op.create_index('ix_candidates_name', 'candidates', ['last_name', 'first_name'], unique=False)
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('fk_applications_resume', 'applications', 'resumes', ['resume_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_applications_application_code'), table_name='applications')
    op.create_index('ix_applications_application_code', 'applications', ['application_code'], unique=False)
    op.create_unique_constraint('uq_applications_application_code', 'applications', ['application_code'])
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    op.create_index('ix_applications_job_status_applied_at', 'applications', ['job_id', 'status', sa.text('applied_at DESC')], unique=False)
    op.create_index('ix_applications_job_id', 'applications', ['job_id'], unique=False)
    op.create_index('ix_applications_candidate_id', 'applications', ['candidate_id'], unique=False)
    op.alter_column('applications', 'resume_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('ix_admins_user_id', 'admins', ['user_id'], unique=False)
    # ### end Alembic commands ###
